-- HELIX recipe seed data
-- Run with: supabase db execute -f supabase/seed/helix_recipes.sql

with data (name, kcal, protein_g, carbs_g, fat_g, diet_type, allergens, prep_time, ingredients, tags) as (
  values
    ('Protein Overnight Oats',
     420, 30, 48, 12,
     'vegetarian',
     ARRAY['milk']::text[],
     5,
     '[{"item":"rolled oats","amount":"60 g"},{"item":"whey protein","amount":"30 g"},{"item":"almond milk","amount":"200 ml"},{"item":"chia seeds","amount":"1 tbsp"}]'::jsonb,
     '{"meal_type":"breakfast","prep":"batch","macro_focus":"balanced"}'::jsonb),
    ('Greek Yogurt Parfait',
     320, 28, 34, 8,
     'omnivore',
     ARRAY['milk']::text[],
     4,
     '[{"item":"plain greek yogurt","amount":"200 g"},{"item":"berries","amount":"100 g"},{"item":"granola","amount":"30 g"},{"item":"honey","amount":"1 tsp"}]'::jsonb,
     '{"meal_type":"breakfast","macro_focus":"high_protein"}'::jsonb),
    ('Smoked Tofu Power Bowl',
     520, 32, 58, 18,
     'vegan',
     ARRAY[]::text[],
     20,
     '[{"item":"smoked tofu","amount":"150 g"},{"item":"quinoa","amount":"120 g cooked"},{"item":"broccoli","amount":"100 g"},{"item":"tahini dressing","amount":"2 tbsp"}]'::jsonb,
     '{"meal_type":"lunch","diet":["vegan"],"macro_focus":"balanced"}'::jsonb),
    ('Citrus Salmon Plate',
     560, 42, 36, 26,
     'pescatarian',
     ARRAY['fish']::text[],
     25,
     '[{"item":"salmon fillet","amount":"150 g"},{"item":"brown rice","amount":"120 g cooked"},{"item":"asparagus","amount":"100 g"},{"item":"citrus glaze","amount":"1 tbsp"}]'::jsonb,
     '{"meal_type":"dinner","diet":["pescatarian"],"macro_focus":"high_protein"}'::jsonb),
    ('Chicken Quinoa Salad',
     510, 46, 48, 16,
     'omnivore',
     ARRAY[]::text[],
     18,
     '[{"item":"grilled chicken breast","amount":"150 g"},{"item":"quinoa","amount":"100 g cooked"},{"item":"mixed greens","amount":"80 g"},{"item":"olive oil vinaigrette","amount":"1 tbsp"}]'::jsonb,
     '{"meal_type":"lunch","macro_focus":"high_protein"}'::jsonb),
    ('Lentil Vegetable Stew',
     430, 24, 62, 10,
     'vegan',
     ARRAY[]::text[],
     35,
     '[{"item":"green lentils","amount":"150 g cooked"},{"item":"carrots","amount":"80 g"},{"item":"celery","amount":"60 g"},{"item":"vegetable broth","amount":"300 ml"}]'::jsonb,
     '{"meal_type":"dinner","diet":["vegan"],"macro_focus":"carb_forward"}'::jsonb),
    ('Egg White Veggie Scramble',
     280, 30, 18, 8,
     'omnivore',
     ARRAY['egg']::text[],
     10,
     '[{"item":"egg whites","amount":"200 g"},{"item":"spinach","amount":"60 g"},{"item":"bell pepper","amount":"50 g"},{"item":"goat cheese","amount":"20 g"}]'::jsonb,
     '{"meal_type":"breakfast","macro_focus":"high_protein"}'::jsonb),
    ('Teriyaki Tempeh Stir-Fry',
     540, 32, 66, 18,
     'vegan',
     ARRAY['soy']::text[],
     22,
     '[{"item":"tempeh","amount":"140 g"},{"item":"stir-fry vegetables","amount":"150 g"},{"item":"brown rice","amount":"130 g cooked"},{"item":"teriyaki sauce","amount":"2 tbsp"}]'::jsonb,
     '{"meal_type":"dinner","diet":["vegan"],"macro_focus":"balanced"}'::jsonb),
    ('Grass-Fed Steak & Sweet Potato',
     610, 48, 45, 24,
     'omnivore',
     ARRAY[]::text[],
     28,
     '[{"item":"sirloin steak","amount":"160 g"},{"item":"sweet potato","amount":"200 g"},{"item":"green beans","amount":"80 g"},{"item":"butter","amount":"1 tsp"}]'::jsonb,
     '{"meal_type":"dinner","macro_focus":"high_protein"}'::jsonb),
    ('Low-FODMAP Turkey Lettuce Wraps',
     360, 32, 24, 14,
     'lowFODMAP',
     ARRAY[]::text[],
     15,
     '[{"item":"ground turkey","amount":"140 g"},{"item":"butter lettuce leaves","amount":"4 leaves"},{"item":"carrot ribbons","amount":"40 g"},{"item":"ginger sesame sauce","amount":"1 tbsp"}]'::jsonb,
     '{"meal_type":"lunch","diet":["lowFODMAP"],"macro_focus":"balanced"}'::jsonb),
    ('Protein Berry Smoothie',
     300, 28, 36, 6,
     'vegetarian',
     ARRAY['milk']::text[],
     3,
     '[{"item":"whey protein","amount":"30 g"},{"item":"frozen berries","amount":"120 g"},{"item":"spinach","amount":"40 g"},{"item":"almond milk","amount":"250 ml"}]'::jsonb,
     '{"meal_type":"snack","macro_focus":"high_protein"}'::jsonb),
    ('Mediterranean Chickpea Bowl',
     480, 20, 60, 16,
     'vegetarian',
     ARRAY[]::text[],
     15,
     '[{"item":"chickpeas","amount":"150 g cooked"},{"item":"farro","amount":"100 g cooked"},{"item":"cucumber","amount":"70 g"},{"item":"tahini lemon dressing","amount":"1.5 tbsp"}]'::jsonb,
     '{"meal_type":"lunch","diet":["vegetarian"],"macro_focus":"balanced"}'::jsonb)
)
insert into recipes (name, kcal, protein_g, carbs_g, fat_g, diet_type, allergens, prep_time, ingredients, tags)
select d.name, d.kcal, d.protein_g, d.carbs_g, d.fat_g, d.diet_type, d.allergens, d.prep_time, d.ingredients, d.tags
from data as d
where not exists (
  select 1 from recipes r where r.name = d.name
);
